### ISSUE TITLE
AppCrash: multiprocessing.context.TimeoutError

### ISSUE THREAD

**Issue by JakubChecinski** [LemurPwned/VISM#133]
**Describe the bug**
The app crashes after loading 0520nm dataset and choosing 3D arrows widget

**Indicate the dataset**
Example 0520nm dataset

**To Reproduce**
1. Load 0520 nm dataset
2. Click Add widget -> 3D Arrow -> Add
3. Don't change any options and click ok
4. App crashes

**Screenshots**
https://imgur.com/wBvXcRG

**Desktop (please complete the following information):**
Windows7

**Comment by LemurPwned** [comment]
Fixed in #156 by adding a Pop Up warning
