### ISSUE TITLE
AppCrash: KeyError: 'toolbar'

### ISSUE THREAD

**Issue by JakubChecinski** [LemurPwned/VISM#139]
**Describe the bug**
2D_BetterPlot crashes the app

**Indicate the dataset**
Examples->0200nm

**To Reproduce**
1. Load data
2. Try to make 2D_BetterPlot widget without changing any options

**Screenshots**
https://imgur.com/hvxUwsP

**Comment by LemurPwned** [comment]
OK Widget plot is considered outdated. I have forgotten to remove it.
We will discuss if OpenGL 2D plots will be in a final version later.
