### ISSUE TITLE
Enter text window survives widget deletion

### ISSUE THREAD

**Issue by JakubChecinski** [LemurPwned/VISM#147]
**Describe the bug**
When I delete a widget with text box added and then add another 3D widget, the old text box is still there

**Indicate the dataset**
A single file from 0200 nm dataset

**To Reproduce**
1. Load data
2. Add 3D widget
3. Add text box anywhere
4. Delete widget, then add any 3D widget again
5. The old text box is now displayed again

**Comment by LemurPwned** [comment]
Will be solved with #148

**Comment by LemurPwned** [comment]
Should be solved now
